services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=fileshare
      - POSTGRES_PASSWORD=fileshare
      - POSTGRES_DB=fileshare
    volumes:
      - fileshare_db:/var/lib/postgresql/data
  redis:
    image: redis:7
  api:
    build: apps/api
  web:
    build: apps/web
    ports:
      - "3069:3069"

volumes:
  fileshare_db:
      
